Removed a ;
UnassignedReferenceException: The variable creatureBuilderWindow of PartDragging has not been assigned.
You probably need to assign the creatureBuilderWindow variable of the PartDragging script in the inspector.
UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at <41b87322553648a1a76174c5109c71f9>:0)
UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at <41b87322553648a1a76174c5109c71f9>:0)
UnityEngine.RectTransform.get_rect () (at <41b87322553648a1a76174c5109c71f9>:0)
UnityEngine.RectTransform.GetLocalCorners (UnityEngine.Vector3[] fourCornersArray) (at <41b87322553648a1a76174c5109c71f9>:0)
UnityEngine.RectTransform.GetWorldCorners (UnityEngine.Vector3[] fourCornersArray) (at <41b87322553648a1a76174c5109c71f9>:0)
CreatureBuilder.PartDragging.GetViewportFromMouse () (at Assets/Scripts/CreatureBuilder/PartDragging.cs:258)
CreatureBuilder.PartDragging.Drag () (at Assets/Scripts/CreatureBuilder/PartDragging.cs:163)
CreatureBuilder.PartDragging.Update () (at Assets/Scripts/CreatureBuilder/PartDragging.cs:62)